name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.cbolich }}
        password: ${{ secrets.dckr_pat_FBNVS6HSA7hbiLCMPuqqSUGiQjk }}

    - name: Build and push FastAPI app image
      uses: docker/build-push-action@v2
      with:
        context: ./app
        push: true
        tags: cbolich/my_fastapi_app:latest

    - name: Build and push Nginx image
      uses: docker/build-push-action@v2
      with:
        context: ./nginx
        push: true
        tags: cbolich/my_nginx_proxy:latest
